models.py
from typing import List
from sqlalchemy import String, Boolean, ForeignKey, DateTime
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from datetime import datetime

# Define the base class for declarative models
class Base(DeclarativeBase):
    pass

# Define the User model
class User(Base):
    __tablename__ = 'users'

    user_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    username: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    password: Mapped[str] = mapped_column(String, nullable=False)

    # Define a relationship to the Task model
    tasks: Mapped[List["Task"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"User(user_id={self.user_id!r}, username={self.username!r})"

# Define the Task model
class Task(Base):
    __tablename__ = 'tasks'

    task_id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    is_completed: Mapped[bool] = mapped_column(Boolean, default=False)
    user_id: Mapped[int] = mapped_column(ForeignKey('users.user_id'), nullable=False)
    description: Mapped[str|None]

    # Define a relationship to the User model
    user: Mapped[User] = relationship(
        back_populates="tasks"
    )

    def __repr__(self) -> str:
        return f"Task(task_id={self.task_id!r}, title={self.title!r}, is_completed={self.is_completed!r})"

auth.py
from hashlib import sha1

import jwt

from flask import Blueprint, redirect, render_template, request, session, url_for

from crud_db import insert_user, is_username_occupied, select_user_by_username_password
from app_init import app

bp = Blueprint("auth", __name__, url_prefix="/auth",template_folder="templates/auth")


@bp.get("/sign_up")
def get_sign_up_page():
    message = session.get("message")

    session.clear()

    return render_template("sign_up.html", message=message)

@bp.post("/sign_up")
def sign_up():
    username = request.form.get("username")
    password = request.form.get("password")
    error = None
    # we don’t need to return anything in case the sign-up finishes successfully.
    status_code = 204
    if not username:
        # say to a user that the request is invalid - missed username
        error, status_code = "Username is required.", 400
    elif not password:
        # say to a user that the request is invalid - missed password
        error, status_code = "Password is required.", 400
    elif is_username_occupied(username):
        # say that the provided username leads to a conflict in the system
        error, status_code = "Username already exists.", 409

    if error:
        session["message"] = {"content": error, "is_error": True}

        return redirect(url_for(".sign_up"))

    insert_user((username, sha1(password.encode()).hexdigest()))
    session["message"] = {"content": "User was successfully created.", "is_error": False}

    return redirect(url_for(".login"))


@bp.get("/login")
def get_login_page():
    message = session.get("message")

    session.clear()

    return render_template("login.html", message=message)


@bp.post("/login")
def login():
    username = request.form.get("username")

    password = request.form.get("password")

    error = None

    user = select_user_by_username_password(username, sha1(password.encode()).hexdigest())

    if not username:
        error = "Username is required."

    elif not password:
        error = "Password is required."

    elif not user:
        error = "Username or password invalid."

    if error:
        session["message"] = {"content": error, "is_error": True}

        return redirect(url_for(".login"))

    token = jwt.encode({"username": username, "user_id": user.user_id}, app.secret_key)

    session["token"] = token

    return redirect(url_for("tasks.list_tasks"))


@bp.post("/logout")
def logout():
    session.clear()

    return redirect(url_for("auth.login"))

main.py
import auth
import views
from app_init import create_app

app = create_app(views, auth)

if __name__ == "__main__":

    app.run(debug=True)

views.py
from datetime import datetime
from functools import wraps

import jwt
from flask import Blueprint, make_response, request, session, redirect, url_for, render_template

from app_init import app
from crud_db import (
    insert_task,
    get_user_task_by_id,
    get_completed_tasks,
    update_task,
    delete_task,
    select_user_by_user_id,
)

# https://flask.palletsprojects.com/en/2.3.x/tutorial/views/
bp = Blueprint("tasks", __name__, template_folder="templates/tasks")


def auth_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        token = session.get("token")

        if not token:
            return redirect(url_for("auth.login"))

        try:
            payload = jwt.decode(token, app.secret_key, "HS256")

            username = payload["username"]
            user_id = payload["user_id"]
            user = select_user_by_user_id(user_id)

            if not user:
                return redirect(url_for("auth.login"))

            session["username"] = username
            session["user_id"] = user.user_id

        except jwt.exceptions.DecodeError:

            return redirect(url_for("auth.login"))

        return func(user, *args, **kwargs)

    return wrapper


@bp.get("/")
@auth_required
def list_tasks(user):
    completed_flag = request.args.get("completed", "false").lower()  # fetch the query parameter
    # check that query parameter has valid value
    if completed_flag.lower() not in ("true", "false"):
       # say to a user that the request is invalid
        return make_response(
            {"message": "Wrong value for `completed`. Expected `true` or `false`."},
            400,
        )

    flag_mapping = {"true": True, "false": False}[completed_flag]

    if flag_mapping:
        # filter only not completed tasks
        tasks = get_completed_tasks(user.user_id, flag_mapping)
    else:
        # return all user tasks if query parameter was not provided
        tasks = user.tasks

    return render_template(
        "dashboard.html",
        is_completed=flag_mapping,
        tasks=[t.__dict__ for t in tasks],
    )


@bp.get("/new_task")
@auth_required
def get_create_task_page(user):
    return render_template("new_task.html")


@bp.post("/new_task")
@auth_required
def create_task(user):
    task_info = (
        request.form.get("title", "Missed title"),  # get `title` from the request body
        datetime.now(),  # get current time
        False,  # by default a new task is not completed
        user.user_id,
        request.form.get("description"),
    )

    insert_task(task_info)  # save the task in the storage

    return redirect(url_for("tasks.list_tasks"))


@bp.get("/complete/<task_id>")
@auth_required
def mark_completed(user, task_id):
    # filter user tasks and find task by the provided ID from the path
    task = get_user_task_by_id(user.user_id, task_id)

    if not task:
        # say to a user that the task with provided ID doesn't exist
        return make_response({"message": "Task not found"}, 404)

    update_task(task_id, task.title, True) # mark the task as completed

    return redirect(url_for("tasks.list_tasks"))


@bp.get("/delete/<task_id>")
@auth_required
def delete(user, task_id):
    # filter user tasks
    task = get_user_task_by_id(user.user_id, task_id)

    if not task:  # check that user try to delete own task
        # say to a user that the task with provided ID doesn't exist
        return make_response({"message": "Task not found"}, 404)

    delete_task(task_id)  # delete task by the provided ID from the path

    return redirect(url_for("tasks.list_tasks"))

templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}TaskManager{% endblock %}</title>
</head>

<body>
    <main>
        {% block content %}
        <!-- Page-specific content goes here -->
        {% endblock %}

    </main>
    <footer>
        <p>{% block footer %}© 2024 TaskManager{% endblock %}</p>
    </footer>
</body>
</html>

templates/tasks/base.html
{% extends "base.html" %} 

{% block content %} 

<br/>
<div>
    <form action="{{ url_for('auth.logout') }}" method="post">
        <button type="submit">Log Out</button>
    </form>
</div>
<br/>
{% block task %} 

{% endblock %} 



{% endblock %} 

templates/tasks/dashboard.html
{% extends "tasks/base.html" %} 

{% block title %}User Tasks{% endblock %} 

{% block task %} 

<h2>Your Tasks, {{ session['username'] }}</h2> 
<br/>
<table>
<tr>
    <td>
    <form action="{{ url_for('tasks.create_task') }}" method="get">
        <button type="submit">Create New Task</button>
    </form>
    </td>
    <td>
        <label for="completed">Show completed tasks</label>
        <input type="checkbox" id="completed" name="completed"  {% if is_completed %} checked {%endif%} onclick="window.location.href = '/?completed={{not is_completed}}' ; ">
    </td>
</tr>
</table>
<br/>
{% if tasks %} 

    <table border="1" cellpadding="5" cellspacing="0" style="width: 100%; border-collapse: collapse;">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Created At</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.created_at }}</td>
                <td>{{ "Completed" if task.is_completed else "Not Completed" }}</td>
                <td>
                    {% if not task.is_completed %}
                    <a href="{{ url_for('tasks.mark_completed', task_id=task.task_id) }}">Complete Task</a>
                    <br/><br/>
                    {% endif %}
                    <a href="{{ url_for('tasks.delete', task_id=task.task_id) }}">Delete Task</a>
                </td>
            </tr>
            {% endfor %}


        </tbody>
    </table>
{% else %}
    <p>No tasks available. Create a new task below.</p>
{% endif %} 

{% endblock %}

templates/tasks/new_task.html
{% extends "tasks/base.html" %} 

{% block title %}Create New Task{% endblock %} 

{% block task %} 

<h2>Create a New Task</h2> 

<form action="{{ url_for('tasks.create_task') }}" method="post">
    <label for="title">Task Title:</label><br>
    <input type="text" id="title" name="title" required><br><br>
    <label for="description">Task Description:</label><br>
    <input type="text" id="description" name="description"><br><br>
    <button type="submit">Create Task</button>
</form> 

<div>
    <form action="{{ url_for('tasks.list_tasks') }}" method="get">
        <button type="submit">Back to Tasks</button>
    </form>
</div>
{% endblock %}